In [1]:
import pandas as pd
df_apt = pd.read_excel('./data/아파트(매매)_실거래가_orig.xlsx',skiprows=12,thousands=",")
df_apt

C:\Users\dlsgh\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
0,1,서울특별시 동대문구 장안동,336,336,0,장안현대홈타운(336),84.870,202412,31,96500,...,18,개인,개인,2003,장한로18길 82-14,-,중개거래,서울 동대문구,25.03.04,아파트
1,2,서울특별시 광진구 광장동,576,576,0,광장현대9단지,59.970,202412,31,112500,...,4,개인,개인,1999,아차산로69길 19,-,중개거래,서울 광진구,25.02.28,아파트
2,3,서울특별시 용산구 동자동,19-8,19,8,동자,27.340,202412,31,44000,...,3,개인,개인,1969,한강대로104마길 30,-,중개거래,서울 용산구,25.01.13,아파트
3,4,서울특별시 종로구 홍파동,199,199,0,경희궁자이(2단지),84.614,202412,31,233000,...,4,개인,개인,2017,송월길 99,-,중개거래,서울 종로구,25.03.27,아파트
4,5,서울특별시 동대문구 용두동,792,792,0,래미안 허브리츠,59.980,202412,31,105800,...,10,개인,개인,2011,정릉천동로 36,-,중개거래,서울 동대문구,25.03.17,아파트
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57206,57207,서울특별시 도봉구 쌍문동,731,731,0,e편한세상,84.978,202401,1,61000,...,1,개인,개인,2007,노해로41가길 16,-,중개거래,서울 도봉구,24.02.26,아파트
57207,57208,서울특별시 은평구 진관동,102,102,0,박석고개1단지힐스테이트(116~131동)BL2-1,84.720,202401,1,97000,...,13,개인,개인,2009,진관1로 21-10,-,중개거래,서울 은평구,24.02.19,아파트
57208,57209,서울특별시 송파구 가락동,53,53,0,"가락3차쌍용스윗닷홈101동,102동",59.940,202401,1,100000,...,11,개인,개인,2005,송이로21길 23,-,중개거래,서울 송파구,24.03.26,아파트
57209,57210,서울특별시 송파구 가락동,165,165,0,래미안파크팰리스,84.885,202401,1,149000,...,5,개인,개인,2007,동남로 225,-,중개거래,서울 송파구,24.02.20,아파트
57210,57211,서울특별시 강동구 상일동,519,519,0,고덕아르테온,59.980,202401,1,117500,...,10,개인,개인,2020,고덕로 360,-,중개거래,서울 강동구,24.02.26,아파트

In [2]:
df_apt.rename(columns={"전용면적(㎡)":"전용면적"}, inplace=True)
df_apt.rename(columns={"거래금액(만원)":"거래금액"}, inplace=True)
df_apt['평'] = round(df_apt["전용면적"] / 3.306,1)
df_apt['거래금액_억'] = df_apt['거래금액']/10000
df_apt['계약년'] = df_apt['계약년월'] // 100
df_apt['계약월'] = df_apt['계약년월'] % 100
df_apt

,NO,시군구,번지,본번,부번,단지명,전용면적,계약년월,계약일,거래금액,...,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형,평,거래금액_억,계약년,계약월
0,1,서울특별시 동대문구 장안동,336,336,0,장안현대홈타운(336),84.870,202412,31,96500,...,장한로18길 82-14,-,중개거래,서울 동대문구,25.03.04,아파트,25.7,9.65,2024,12
1,2,서울특별시 광진구 광장동,576,576,0,광장현대9단지,59.970,202412,31,112500,...,아차산로69길 19,-,중개거래,서울 광진구,25.02.28,아파트,18.1,11.25,2024,12
2,3,서울특별시 용산구 동자동,19-8,19,8,동자,27.340,202412,31,44000,...,한강대로104마길 30,-,중개거래,서울 용산구,25.01.13,아파트,8.3,4.40,2024,12
3,4,서울특별시 종로구 홍파동,199,199,0,경희궁자이(2단지),84.614,202412,31,233000,...,송월길 99,-,중개거래,서울 종로구,25.03.27,아파트,25.6,23.30,2024,12
4,5,서울특별시 동대문구 용두동,792,792,0,래미안 허브리츠,59.980,202412,31,105800,...,정릉천동로 36,-,중개거래,서울 동대문구,25.03.17,아파트,18.1,10.58,2024,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57206,57207,서울특별시 도봉구 쌍문동,731,731,0,e편한세상,84.978,202401,1,61000,...,노해로41가길 16,-,중개거래,서울 도봉구,24.02.26,아파트,25.7,6.10,2024,1
57207,57208,서울특별시 은평구 진관동,102,102,0,박석고개1단지힐스테이트(116~131동)BL2-1,84.720,202401,1,97000,...,진관1로 21-10,-,중개거래,서울 은평구,24.02.19,아파트,25.6,9.70,2024,1
57208,57209,서울특별시 송파구 가락동,53,53,0,"가락3차쌍용스윗닷홈101동,102동",59.940,202401,1,100000,...,송이로21길 23,-,중개거래,서울 송파구,24.03.26,아파트,18.1,10.00,2024,1
57209,57210,서울특별시 송파구 가락동,165,165,0,래미안파크팰리스,84.885,202401,1,149000,...,동남로 225,-,중개거래,서울 송파구,24.02.20,아파트,25.7,14.90,2024,1
57210,57211,서울특별시 강동구 상일동,519,519,0,고덕아르테온,59.980,202401,1,117500,...,고덕로 360,-,중개거래,서울 강동구,24.02.26,아파트,18.1,11.75,2024,1

In [3]:
import numpy as np
# 10평이하, 10평대, 20평개, 30평대, 30평이상
df_apt['평형'] = np.where(df_apt['평'] < 10,'10평이하',
        np.where(df_apt['평'] < 20,'10평대',
                 np.where(df_apt['평'] < 30,'20평대',
                          np.where(df_apt['평'] < 40, '30평대','30평이상'
                                  )
                         )
                )
        )
df_apt['평형']

0         20평대
1         10평대
2        10평이하
3         20평대
4         10평대
         ...
57206     20평대
57207     20평대
57208     10평대
57209     20평대
57210     10평대
Name: 평형, Length: 57211, dtype: object

In [4]:
df_apt.query('거래금액_억 > 100')

,NO,시군구,번지,본번,부번,단지명,전용면적,계약년월,계약일,거래금액,...,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형,평,거래금액_억,계약년,계약월,평형
603,604,서울특별시 서초구 반포동,1,1,0,래미안원베일리,133.9500,202412,26,1060000,...,-,중개거래,서울 서초구,-,아파트,40.5,106.0,2024,12,30평이상
2874,2875,서울특별시 강남구 청담동,129,129,0,PH129,273.9600,202412,5,1380000,...,-,중개거래,서울 서초구,25.01.31,아파트,82.9,138.0,2024,12,30평이상
7825,7826,서울특별시 용산구 한남동,410,410,0,파르크한남,268.9500,202410,22,1700000,...,-,중개거래,서울 용산구,25.01.06,아파트,81.4,170.0,2024,10,30평이상
8307,8308,서울특별시 강남구 청담동,129,129,0,PH129,273.9600,202410,18,1024000,...,-,직거래,-,24.11.29,아파트,82.9,102.4,2024,10,30평이상
10673,10674,서울특별시 용산구 한남동,810,810,0,한남더힐,233.0620,202409,30,1060000,...,-,중개거래,서울 용산구,24.10.30,아파트,70.5,106.0,2024,9,30평이상
19610,19611,서울특별시 서초구 반포동,2-12,2,12,아크로리버파크,234.9100,202408,5,1800000,...,-,중개거래,서울 서초구,24.08.29,아파트,71.1,180.0,2024,8,30평이상
20303,20304,서울특별시 용산구 한남동,829,829,0,나인원한남,206.8953,202407,31,1100000,...,-,중개거래,서울 용산구,24.08.09,아파트,62.6,110.0,2024,7,30평이상
22994,22995,서울특별시 용산구 한남동,829,829,0,나인원한남,273.4125,202407,22,2200000,...,-,직거래,-,-,아파트,82.7,220.0,2024,7,30평이상
26649,26650,서울특별시 성동구 성수동1가,685-700,685,700,아크로서울포레스트,159.6030,202407,10,1100000,...,-,중개거래,서울 성동구,25.04.01,아파트,48.3,110.0,2024,7,30평이상
28403,28404,서울특별시 성동구 성수동1가,685-700,685,700,아크로서울포레스트,198.2190,202407,4,1450000,...,-,중개거래,"서울 강남구, 서울 성동구",25.04.10,아파트,60.0,145.0,2024,7,30평이상
34205,34206,서울특별시 강남구 압구정동,456,456,0,"현대7차(73~77,82,85동)",245.2000,202406,14,1150000,...,-,중개거래,서울 강남구,24.10.22,아파트,74.2,115.0,2024,6,30평이상
36541,36542,서울특별시 용산구 한남동,829,829,0,나인원한남,273.9424,202406,4,2000000,...,-,중개거래,서울 용산구,24.07.15,아파트,82.9,200.0,2024,6,30평이상
36549,36550,서울특별시 성동구 성수동1가,685-696,685,696,갤러리아포레,241.9300,202406,4,1080000,...,-,중개거래,"서울 구로구, 서울 용산구",24.10.28,아파트,73.2,108.0,2024,6,30평이상
41349,41350,서울특별시 성동구 성수동1가,685-700,685,700,아크로서울포레스트,200.6730,202405,9,1090000,...,-,중개거래,"서울 강남구, 서울 성동구",24.07.17,아파트,60.7,109.0,2024,5,30평이상
45661,45662,서울특별시 용산구 한남동,829,829,0,나인원한남,244.3478,202404,11,1200000,...,-,중개거래,"서울 강남구, 서울 용산구",24.05.13,아파트,73.9,120.0,2024,4,30평이상
45877,45878,서울특별시 용산구 한남동,810,810,0,한남더힐,240.2300,202404,10,1200000,...,-,중개거래,서울 강남구,24.06.17,아파트,72.7,120.0,2024,4,30평이상
45879,45880,서울특별시 용산구 한남동,810,810,0,한남더힐,240.2300,202404,10,1200000,...,20240507,중개거래,서울 강남구,-,아파트,72.7,120.0,2024,4,30평이상
46013,46014,서울특별시 용산구 한남동,829,829,0,나인원한남,206.8953,202404,9,1030000,...,-,중개거래,서울 성동구,-,아파트,62.6,103.0,2024,4,30평이상
48042,48043,서울특별시 강남구 압구정동,456,456,0,"현대7차(73~77,82,85동)",245.2000,202403,27,1150000,...,-,직거래,-,24.04.22,아파트,74.2,115.0,2024,3,30평이상
51163,51164,서울특별시 강남구 청담동,129,129,0,PH129,273.9600,202403,6,1030000,...,-,중개거래,서울 강남구,24.05.30,아파트,82.9,103.0,2024,3,30평이상

In [5]:
# 거래금액이 100억 이상인 행
apt_100 = df_apt.query('거래금액_억 > 100')
apt_100.shape

(20, 26)

In [6]:
# 10평 이하인 거래건수
df_apt.query('평 < 10').shape

(2445, 26)

In [7]:
"abc".count('a')
'a,b,c'.split(",")

['a', 'b', 'c']

In [8]:
# df_apt['시군구'].str.split().str[0] #시
df_apt['구'] = df_apt['시군구'].str.split().str[1] #구
df_apt['동'] = df_apt['시군구'].str.split().str[2] #동
type(df_apt[['구','동']])

pandas.core.frame.DataFrame

In [9]:
# 강남구 거래건수
df_apt.query("구 == '강남구'").shape

(3686, 27)

In [10]:
df_apt['구'].value_counts()

구
송파구     4294
노원구     4203
강남구     3686
강동구     3410
서초구     3039
성북구     3009
영등포구    2949
성동구     2875
강서구     2835
마포구     2680
양천구     2549
동작구     2496
동대문구    2448
구로구     2287
서대문구    2285
은평구     2076
도봉구     1589
중랑구     1580
관악구     1484
광진구     1388
용산구     1088
강북구      904
중구       854
금천구      754
종로구      449
Name: count, dtype: int64

In [11]:
pd.set_option('display.max_columns', None)

In [12]:
df_apt

,NO,시군구,번지,본번,부번,단지명,전용면적,계약년월,계약일,거래금액,동,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형,평,거래금액_억,계약년,계약월,평형,구
0,1,서울특별시 동대문구 장안동,336,336,0,장안현대홈타운(336),84.870,202412,31,96500,장안동,18,개인,개인,2003,장한로18길 82-14,-,중개거래,서울 동대문구,25.03.04,아파트,25.7,9.65,2024,12,20평대,동대문구
1,2,서울특별시 광진구 광장동,576,576,0,광장현대9단지,59.970,202412,31,112500,광장동,4,개인,개인,1999,아차산로69길 19,-,중개거래,서울 광진구,25.02.28,아파트,18.1,11.25,2024,12,10평대,광진구
2,3,서울특별시 용산구 동자동,19-8,19,8,동자,27.340,202412,31,44000,동자동,3,개인,개인,1969,한강대로104마길 30,-,중개거래,서울 용산구,25.01.13,아파트,8.3,4.40,2024,12,10평이하,용산구
3,4,서울특별시 종로구 홍파동,199,199,0,경희궁자이(2단지),84.614,202412,31,233000,홍파동,4,개인,개인,2017,송월길 99,-,중개거래,서울 종로구,25.03.27,아파트,25.6,23.30,2024,12,20평대,종로구
4,5,서울특별시 동대문구 용두동,792,792,0,래미안 허브리츠,59.980,202412,31,105800,용두동,10,개인,개인,2011,정릉천동로 36,-,중개거래,서울 동대문구,25.03.17,아파트,18.1,10.58,2024,12,10평대,동대문구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57206,57207,서울특별시 도봉구 쌍문동,731,731,0,e편한세상,84.978,202401,1,61000,쌍문동,1,개인,개인,2007,노해로41가길 16,-,중개거래,서울 도봉구,24.02.26,아파트,25.7,6.10,2024,1,20평대,도봉구
57207,57208,서울특별시 은평구 진관동,102,102,0,박석고개1단지힐스테이트(116~131동)BL2-1,84.720,202401,1,97000,진관동,13,개인,개인,2009,진관1로 21-10,-,중개거래,서울 은평구,24.02.19,아파트,25.6,9.70,2024,1,20평대,은평구
57208,57209,서울특별시 송파구 가락동,53,53,0,"가락3차쌍용스윗닷홈101동,102동",59.940,202401,1,100000,가락동,11,개인,개인,2005,송이로21길 23,-,중개거래,서울 송파구,24.03.26,아파트,18.1,10.00,2024,1,10평대,송파구
57209,57210,서울특별시 송파구 가락동,165,165,0,래미안파크팰리스,84.885,202401,1,149000,가락동,5,개인,개인,2007,동남로 225,-,중개거래,서울 송파구,24.02.20,아파트,25.7,14.90,2024,1,20평대,송파구
57210,57211,서울특별시 강동구 상일동,519,519,0,고덕아르테온,59.980,202401,1,117500,상일동,10,개인,개인,2020,고덕로 360,-,중개거래,서울 강동구,24.02.26,아파트,18.1,11.75,2024,1,10평대,강동구

In [13]:
# 강남구 거래건수 출력
gu = "종로구"
df_apt.query('구 == @gu').shape

(449, 27)

In [14]:
# 강남구 10평대 아파트 거래건수 출력
df_apt.query('구 == "강남구" & 평형 == "10평대"')['NO'].count()
# for gu in df_apt['구'].unique():
#     print(gu)

1119

In [15]:
# 서울 모든 구 10평대 아파트 거래건수 출력
for gu in df_apt["구"].unique():
    cnt = df_apt.query("구 == @gu & 평형 == '10평대'")['NO'].count()
    print(cnt)

934
416
314
149
294
1255
2516
1422
639
714
1333
935
1132
368
1075
659
611
855
1119
868
913
1084
1408
1190
378

In [16]:
df_apt

,NO,시군구,번지,본번,부번,단지명,전용면적,계약년월,계약일,거래금액,동,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형,평,거래금액_억,계약년,계약월,평형,구
0,1,서울특별시 동대문구 장안동,336,336,0,장안현대홈타운(336),84.870,202412,31,96500,장안동,18,개인,개인,2003,장한로18길 82-14,-,중개거래,서울 동대문구,25.03.04,아파트,25.7,9.65,2024,12,20평대,동대문구
1,2,서울특별시 광진구 광장동,576,576,0,광장현대9단지,59.970,202412,31,112500,광장동,4,개인,개인,1999,아차산로69길 19,-,중개거래,서울 광진구,25.02.28,아파트,18.1,11.25,2024,12,10평대,광진구
2,3,서울특별시 용산구 동자동,19-8,19,8,동자,27.340,202412,31,44000,동자동,3,개인,개인,1969,한강대로104마길 30,-,중개거래,서울 용산구,25.01.13,아파트,8.3,4.40,2024,12,10평이하,용산구
3,4,서울특별시 종로구 홍파동,199,199,0,경희궁자이(2단지),84.614,202412,31,233000,홍파동,4,개인,개인,2017,송월길 99,-,중개거래,서울 종로구,25.03.27,아파트,25.6,23.30,2024,12,20평대,종로구
4,5,서울특별시 동대문구 용두동,792,792,0,래미안 허브리츠,59.980,202412,31,105800,용두동,10,개인,개인,2011,정릉천동로 36,-,중개거래,서울 동대문구,25.03.17,아파트,18.1,10.58,2024,12,10평대,동대문구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57206,57207,서울특별시 도봉구 쌍문동,731,731,0,e편한세상,84.978,202401,1,61000,쌍문동,1,개인,개인,2007,노해로41가길 16,-,중개거래,서울 도봉구,24.02.26,아파트,25.7,6.10,2024,1,20평대,도봉구
57207,57208,서울특별시 은평구 진관동,102,102,0,박석고개1단지힐스테이트(116~131동)BL2-1,84.720,202401,1,97000,진관동,13,개인,개인,2009,진관1로 21-10,-,중개거래,서울 은평구,24.02.19,아파트,25.6,9.70,2024,1,20평대,은평구
57208,57209,서울특별시 송파구 가락동,53,53,0,"가락3차쌍용스윗닷홈101동,102동",59.940,202401,1,100000,가락동,11,개인,개인,2005,송이로21길 23,-,중개거래,서울 송파구,24.03.26,아파트,18.1,10.00,2024,1,10평대,송파구
57209,57210,서울특별시 송파구 가락동,165,165,0,래미안파크팰리스,84.885,202401,1,149000,가락동,5,개인,개인,2007,동남로 225,-,중개거래,서울 송파구,24.02.20,아파트,25.7,14.90,2024,1,20평대,송파구
57210,57211,서울특별시 강동구 상일동,519,519,0,고덕아르테온,59.980,202401,1,117500,상일동,10,개인,개인,2020,고덕로 360,-,중개거래,서울 강동구,24.02.26,아파트,18.1,11.75,2024,1,10평대,강동구

In [17]:
df_apt.query("주택유형 == '아파트'").sort_values('거래금액').head(1)

,NO,시군구,번지,본번,부번,단지명,전용면적,계약년월,계약일,거래금액,동,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형,평,거래금액_억,계약년,계약월,평형,구
34567,34568,서울특별시 도봉구 창동,7,7,0,월가타워,13.02,202406,12,7000,창동,15,개인,개인,2013,마들로11가길 6-25,-,중개거래,서울 도봉구,24.06.18,아파트,3.9,0.7,2024,6,10평이하,도봉구

In [18]:
df_apt.query("주택유형 == '아파트'").sort_values('거래금액').tail(1)

,NO,시군구,번지,본번,부번,단지명,전용면적,계약년월,계약일,거래금액,동,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형,평,거래금액_억,계약년,계약월,평형,구
22994,22995,서울특별시 용산구 한남동,829,829,0,나인원한남,273.4125,202407,22,2200000,한남동,1,개인,개인,2019,한남대로 91,-,직거래,-,-,아파트,82.7,220.0,2024,7,30평이상,용산구

In [19]:
df_apt.query("주택유형 == '아파트'").sort_values('전용면적').head(1)

,NO,시군구,번지,본번,부번,단지명,전용면적,계약년월,계약일,거래금액,동,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형,평,거래금액_억,계약년,계약월,평형,구
48061,48062,서울특별시 동대문구 이문동,327-7,327,7,세진빌딩,11.48,202403,27,20000,이문동,13,개인,개인,2020,이문로 89,-,직거래,-,24.04.09,아파트,3.5,2.0,2024,3,10평이하,동대문구

In [20]:
df_apt.query("주택유형 == '아파트'").sort_values('전용면적').tail(1)

,NO,시군구,번지,본번,부번,단지명,전용면적,계약년월,계약일,거래금액,동,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형,평,거래금액_억,계약년,계약월,평형,구
51163,51164,서울특별시 강남구 청담동,129,129,0,PH129,273.96,202403,6,1030000,청담동,6,개인,개인,2020,압구정로79길 88,-,중개거래,서울 강남구,24.05.30,아파트,82.9,103.0,2024,3,30평이상,강남구

In [21]:
apt_10_max = df_apt.query("평형 == '10평대'")['거래금액'].max()
apt_10_max

388000

In [22]:
df_apt.query("평형 == '20평대' and 거래금액 < @apt_10_max")

,NO,시군구,번지,본번,부번,단지명,전용면적,계약년월,계약일,거래금액,동,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형,평,거래금액_억,계약년,계약월,평형,구
0,1,서울특별시 동대문구 장안동,336,336,0,장안현대홈타운(336),84.870,202412,31,96500,장안동,18,개인,개인,2003,장한로18길 82-14,-,중개거래,서울 동대문구,25.03.04,아파트,25.7,9.65,2024,12,20평대,동대문구
3,4,서울특별시 종로구 홍파동,199,199,0,경희궁자이(2단지),84.614,202412,31,233000,홍파동,4,개인,개인,2017,송월길 99,-,중개거래,서울 종로구,25.03.27,아파트,25.6,23.30,2024,12,20평대,종로구
5,6,서울특별시 중구 신당동,842,842,0,약수하이츠,84.880,202412,31,131000,신당동,10,개인,개인,1999,동호로10길 30,-,중개거래,서울 중구,25.02.27,아파트,25.7,13.10,2024,12,20평대,중구
8,9,서울특별시 성동구 금호동1가,633,633,0,벽산,84.820,202412,31,138500,금호동1가,18,개인,개인,2001,금호로 100,-,중개거래,서울 성동구,25.03.20,아파트,25.7,13.85,2024,12,20평대,성동구
10,11,서울특별시 광진구 광장동,566,566,0,청구,84.860,202412,31,132000,광장동,20,개인,개인,1996,아차산로 503-23,-,중개거래,서울 광진구,25.02.28,아파트,25.7,13.20,2024,12,20평대,광진구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57204,57205,서울특별시 구로구 개봉동,478,478,0,한진,84.960,202401,1,58000,개봉동,11,개인,개인,2000,개봉로3길 87,-,중개거래,서울 구로구,24.04.03,아파트,25.7,5.80,2024,1,20평대,구로구
57205,57206,서울특별시 강북구 미아동,812,812,0,삼성래미안트리베라2단지,84.290,202401,1,80000,미아동,19,개인,개인,2010,삼양로27길 19,-,중개거래,서울 강북구,24.04.15,아파트,25.5,8.00,2024,1,20평대,강북구
57206,57207,서울특별시 도봉구 쌍문동,731,731,0,e편한세상,84.978,202401,1,61000,쌍문동,1,개인,개인,2007,노해로41가길 16,-,중개거래,서울 도봉구,24.02.26,아파트,25.7,6.10,2024,1,20평대,도봉구
57207,57208,서울특별시 은평구 진관동,102,102,0,박석고개1단지힐스테이트(116~131동)BL2-1,84.720,202401,1,97000,진관동,13,개인,개인,2009,진관1로 21-10,-,중개거래,서울 은평구,24.02.19,아파트,25.6,9.70,2024,1,20평대,은평구
57209,57210,서울특별시 송파구 가락동,165,165,0,래미안파크팰리스,84.885,202401,1,149000,가락동,5,개인,개인,2007,동남로 225,-,중개거래,서울 송파구,24.02.20,아파트,25.7,14.90,2024,1,20평대,송파구

In [23]:
# 구별 거래건수.임의의 컬럼 선택
df_apt.groupby("구").agg(count=('층','count'))

      count
구
강남구    3686
강동구    3410
강북구     904
강서구    2835
관악구    1484
광진구    1388
구로구    2287
금천구     754
노원구    4203
도봉구    1589
동대문구   2448
동작구    2496
마포구    2680
서대문구   2285
서초구    3039
성동구    2875
성북구    3009
송파구    4294
양천구    2549
영등포구   2949
용산구    1088
은평구    2076
종로구     449
중구      854
중랑구    1580

In [42]:
# 평형별 거래건수, 평형별 평균거래금액, 평형별 최소거래금액, 평형별 최대거래금액
df_apt.groupby('평형').agg(평형별_거래건수=('평형','count'),
                            평균거래금액=('거래금액','mean'),
                            최소거래금액=('거래금액','min'),
                            최대거래금액=('거래금액','max'))

       평형별_거래건수         평균거래금액  최소거래금액   최대거래금액
평형
10평대      22581   85888.825738   12000   388000
10평이하      2445   25867.110020    7000   126000
20평대      24068  127216.999917   23000   600000
30평대       5537  181647.795738   35000   798000
30평이상      2580  302453.763566   49000  2200000

In [47]:
# 아파트 구별 평형별 거래건수
df_apt.groupby(['구', '평형']) \
   .agg(apt_count = ('구', 'count'))

           apt_count
구   평형
강남구 10평대        1119
    10평이하         80
    20평대        1380
    30평대         609
    30평이상        498
...              ...
중랑구 10평대         639
    10평이하        100
    20평대         718
    30평대         106
    30평이상         17

[125 rows x 1 columns]

In [51]:
df_apt.groupby(['구', '평형'])['층'].count()

구    평형
강남구  10평대     1119
     10평이하      80
     20평대     1380
     30평대      609
     30평이상     498
              ...
중랑구  10평대      639
     10평이하     100
     20평대      718
     30평대      106
     30평이상      17
Name: 층, Length: 125, dtype: int64

In [54]:
df_apt.groupby(['구', '평형']).agg(평균거래금액=('거래금액','mean'))
df_apt.groupby(['구', '평형'])['거래금액'].mean()

             평균거래금액
구   평형
강남구 10평대   152047.0
    10평이하   41406.0
    20평대   233105.0
    30평대   311217.0
    30평이상  470204.0
...             ...
중랑구 10평대    50815.0
    10평이하   18701.0
    20평대    74201.0
    30평대    94084.0
    30평이상   98229.0

[125 rows x 1 columns]